import { defineField, defineType } from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  initialValue: {
    name: 'Shiv Prabha Foundation',
    tagline: 'संस्कार, शिक्षा और सेवा की ओर एक कदम',
    description: 'We work directly on the ground in India\'s most remote blocks to rescue families from dirty water, keep children in school, and equip young talent to escape poverty.',
    url: 'https://shivprabhafoundation.org',
    email: 'hello@shivprabhafoundation.org',
    phone: ['+91 11 4567 8900', '+91 98765 43210'],
    address: { line1: '42, Lodhi Road, Institutional Area', line2: 'New Delhi, Delhi 110003' },
    workingHours: ['Monday – Friday: 9:30 AM – 6:00 PM', 'Saturday: 10:00 AM – 2:00 PM'],
    navLinks: [
      { _key: 'nav-1', label: 'Home', href: '/' },
      { _key: 'nav-2', label: 'About', href: '/about' },
      { _key: 'nav-3', label: 'Programs', href: '/programs' },
      { _key: 'nav-4', label: 'Our Impact', href: '/impact' },
      { _key: 'nav-5', label: 'Stories of Hope', href: '/stories' },
      { _key: 'nav-6', label: 'Gallery', href: '/gallery' },
      { _key: 'nav-7', label: 'Reports', href: '/reports' },
      { _key: 'nav-8', label: 'Contact Us', href: '/contact' },
    ],
    social: {
      facebook: 'https://facebook.com/ngofund',
      twitter: 'https://twitter.com/ngofund',
      instagram: 'https://instagram.com/ngofund',
      linkedin: 'https://linkedin.com/company/ngofund',
      youtube: 'https://youtube.com/@ngofund',
    },
    legal: {
      registrations: [
        'FCRA Registered Organization',
        '80G Tax Exemption Certificate',
        '12A Registration under IT Act',
        'Registered under Societies Registration Act',
      ],
    },
  },
  groups: [
    { name: 'general', title: 'General' },
    { name: 'navigation', title: 'Navigation' },
    { name: 'contact', title: 'Contact' },
    { name: 'social', title: 'Social Links' },
    { name: 'legal', title: 'Legal' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Foundation Name',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Meta Description',
      type: 'text',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'url',
      title: 'Website URL',
      type: 'url',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Contact Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: 'phone',
      title: 'Phone Numbers',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'contact',
    }),
    defineField({
      name: 'address',
      title: 'Address',
      type: 'object',
      group: 'contact',
      fields: [
        { name: 'line1', type: 'string', title: 'Line 1' },
        { name: 'line2', type: 'string', title: 'Line 2' },
      ],
    }),
    defineField({
      name: 'workingHours',
      title: 'Working Hours',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'contact',
    }),
    defineField({
      name: 'navLinks',
      title: 'Navigation Links',
      type: 'array',
      group: 'navigation',
      of: [{
        type: 'object',
        fields: [
          { name: 'label', type: 'string', title: 'Label' },
          { name: 'href', type: 'string', title: 'Path' },
        ],
      }],
    }),
    defineField({
      name: 'footerQuickLinks',
      title: 'Footer Quick Links',
      type: 'array',
      group: 'navigation',
      of: [{
        type: 'object',
        fields: [
          { name: 'label', type: 'string', title: 'Label' },
          { name: 'href', type: 'string', title: 'Path' },
        ],
      }],
    }),
    defineField({
      name: 'footerLegalLinks',
      title: 'Footer Legal Links',
      type: 'array',
      group: 'navigation',
      of: [{
        type: 'object',
        fields: [
          { name: 'label', type: 'string', title: 'Label' },
          { name: 'href', type: 'string', title: 'Path' },
        ],
      }],
    }),
    defineField({
      name: 'social',
      title: 'Social Media Links',
      type: 'object',
      group: 'social',
      fields: [
        { name: 'facebook', type: 'url', title: 'Facebook URL' },
        { name: 'twitter', type: 'url', title: 'Twitter URL' },
        { name: 'instagram', type: 'url', title: 'Instagram URL' },
        { name: 'linkedin', type: 'url', title: 'LinkedIn URL' },
        { name: 'youtube', type: 'url', title: 'YouTube URL' },
      ],
    }),
    defineField({
      name: 'legal',
      title: 'Legal Information',
      type: 'object',
      group: 'legal',
      fields: [
        { name: 'registrations', type: 'array', of: [{ type: 'string' }], title: 'Registrations' },
        { name: 'taxId', type: 'string', title: 'Tax ID' },
      ],
    }),
  ],
})
